import drop from "./script-events-items/dropdownmenu.js";
import menumobile from "./script-events-items/menumobile.js";
import carrinho from "./script-events-items/menuCarrinho.js";
import loginEvent from "./script-events-items/Login.js";
import cadastreseEvent from "./script-events-items/cadastrese.js";
import carroselEvent from "./script-events-items/carrosel.js";
import TabnavEvent from "./script-events-items/tabProdutos.js";
import carroselProdutoEvent from "./script-events-items/carroselpProdutos.js";
import TooltipEvent from "./script-events-items/tooltipbox.js";
import formularioValidarEvent from "./script-events-items/validarFormluario.js";
import carrinhoDeComprasEvent from "./script-events-items/carrinhodeCompras.js";
import entrarLoginEvent from "./script-events-items/entrarLogin.js";
import formularioHeader from "./script-events-items/formularioCadastroLogin.js";

drop();
menumobile();
carrinho();
loginEvent();
cadastreseEvent();
carroselEvent();
TabnavEvent();
carroselProdutoEvent();
TooltipEvent();
formularioValidarEvent();
carrinhoDeComprasEvent();
entrarLoginEvent();
formularioHeader();
